name: Auto-Build and Release

on:
  push:
    branches:
      - master 

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: crypto-rust
            asset_name: crypto-rust-linux
          - os: windows-latest
            artifact_name: crypto-rust.exe
            asset_name: crypto-rust-win.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release Binary
        run: cargo build --release

      - name: Rename Binary
        shell: bash
        run: |
          mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: "(${{ github.sha }})"
          files: target/release/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
